name: Python Lint
description: GitHub Action that lints a Python based repository
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  extra-args:
    required: false
    description: Extra args for pre-commit
    default: ""
  github-token:
    required: true
    description: GitHub token that can checkout the repository. e.g. 'secrets.GITHUB_TOKEN'
    default: ${{ github.token }}
  python-version:
    required: false
    description: Python version to install on the github runner.
    default: ""

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      if: inputs.checkout-repo == 'true'
      with:
        fetch-depth: 0
    - name: Install poetry
      if: hashFiles('pyproject.toml') != ''
      shell: bash
      run: pipx install poetry
    - name: Setup python
      # this will use by default the .python-version of your repo
      if: hashFiles('poetry.lock') != ''
      uses: actions/setup-python@v4
      with:
        cache: "poetry"
        python-version: ${{ inputs.python-version }}
    - name: Setup python
      # this will use by default the .python-version of your repo
      if: hashFiles('poetry.lock') == ''
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install poetry dependencies
      if: hashFiles('pyproject.toml') != ''
      shell: bash
      run: |
        poetry install
    - name: Install pip dependencies
      if: hashFiles('pyproject.toml') == ''
      shell: bash
      run: pip install -e .
    - uses: pre-commit/action@v3.0.0
