name: Python Lint
description: GitHub Action that lints a Python based repository
inputs:
  checkout-repo:
    required: false
    description: Perform checkout as first step of action
    default: "true"
  extra-args:
    required: false
    description: Extra args for pre-commit
    default: ""
  github-token:
    required: true
    description: GitHub token that can checkout the repository. e.g. 'secrets.GITHUB_TOKEN'
    default: ${{ github.token }}
  python-version:
    required: false
    description: Python version to install on the github runner.
    default: "3.12"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      if: inputs.checkout-repo == 'true'
      with:
        fetch-depth: 0
    - name: Setup python
      if: hashFiles('poetry.lock') != ''
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    - uses: pre-commit/action@v3.0.0
      with:
        extra_args: ${{ inputs.extra-args }}
