name: Release

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      executable:
        type: string
        required: false
        default: "python"

jobs:
  CI:
    uses: armand-sauzay/workflows/.github/workflows/python-ci.yaml@v1
  RELEASE:
    name: Release
    needs: [CI]
    runs-on: ubuntu-latest
    outputs:
      new-release-published: ${{ steps.release.outputs.new-release-published }}
      new-release-version: ${{ steps.release.outputs.new-release-version }}
    steps:
      - uses: armand-sauzay/actions-python/release@v1
        id: release
